<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SealMark.App</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
	  <ApplicationIcon>Assets/app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\app.ico" />
    <None Remove="Assets\Fonts\AlibabaPuHuiTi-3-55-Regular.ttf" />
    <None Remove="Assets\Fonts\AlibabaPuHuiTi-3-85-Bold.ttf" />
    <None Remove="Assets\icon\icon.png" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\app.ico" />
    <AvaloniaResource Include="Assets\Fonts\AlibabaPuHuiTi-3-55-Regular.ttf" />
    <AvaloniaResource Include="Assets\Fonts\AlibabaPuHuiTi-3-85-Bold.ttf" />
    <AvaloniaResource Include="Assets\icon\icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.1" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Semi.Avalonia" Version="12.1.0.1" />
    <PackageReference Include="Semi.Avalonia.ColorPicker" Version="12.1.0.1" />
  </ItemGroup>
</Project>
